### ISSUE TITLE
Не получается запустить гейм, ругается с БД 

### ISSUE THREAD

**Issue by loinzz** [NL0bP/Archeage-Server-emulator#25]
03:58:29 [INFO] Program - AAEmu.Game version 3.0.3.0
03:58:29 [INFO] Program - Checking for updates...
03:58:30 [INFO] GameService - Starting daemon: AAEmu.Game
03:58:30 [INFO] IdManager - TaskIdManager successfully initialized
03:58:30 [INFO] LocalizationManager - Loading translations ...
03:58:30 [ERROR] SQLite - Error on SQLite connect: SQLite Error 14: 'unable to open database file'.
03:58:30 [INFO] GameService - Disposing ...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AAEmu.Game.Core.Managers.LocalizationManager.Load() in C:\AAserver2\AAEmu.Game\Core\Managers\LocalizationManager.cs:line 38
   at AAEmu.Game.GameService.StartAsync(CancellationToken cancellationToken) in C:\AAserver2\AAEmu.Game\GameService.cs:line 41
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at AAEmu.Game.Program.Main(String[] args) in C:\AAserver2\AAEmu.Game\Program.cs:line 82
   at AAEmu.Game.Program.<Main>(String[] args)

C:\AAserver2\AAEmu.Game>

**Comment by loinzz** [comment]
методом научного тыка нарыл что ему не хватает файла compact.sqlite3 в директории AAEmu.Game\data\ и таблицы localized_texts в БД. Подскажите пожалуйста, где раздобыть ?:)
